POST http://localhost:4000/api/language/detect
Content-Type: application/json

{
  "text": "The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software."
}

###
POST http://localhost:4000/api/language/detect
Content-Type: application/json

{
  "text": "How are you?"
}

### sentiment
POST http://localhost:4000/api/sentiment
Content-Type: application/json

{
  "text": "I love playing football"
}


###
